language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: 7
        - php: hhvm-nightly

script: ./tests/run.sh -s ./tests/cases

after_failure:
    # Print *.actual content & log content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - composer install --no-interaction --prefer-source

    # Create php.ini & sections.ini
    - cp ./tests/config.sample.neon ./tests/config.neon
    - cp ./tests/php-unix.ini ./tests/php.ini

    - if [ "$TRAVIS_PHP_VERSION" == "hhvm" -o "$TRAVIS_PHP_VERSION" == "hhvm-nightly" ]; then cp ./tests/sections.hhvm.ini ./tests/sections.ini; fi
    - if ! [ "$TRAVIS_PHP_VERSION" == "hhvm" -o "$TRAVIS_PHP_VERSION" == "hhvm-nightly" ]; then cp ./tests/sections.sample.ini ./tests/sections.ini; fi

    # Create MySQL & Postgre database
    - psql -c 'CREATE DATABASE nextras_orm_test' -U postgres
    - mysql -e 'CREATE DATABASE nextras_orm_test;'

    - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
